language: python

python:
- "3.4"
- "3.5"
- "3.6"

dist: trusty  # beta, but it has docker
sudo: false
addons:
  apt:
    packages:
    - enchant
    - aspell
    - aspell-en

services:
- docker

install:
- pip install -r requirements-dev.txt
- pip install codecov
- pip install elasticsearch
- docker pull elasticsearch:1.7
- docker pull elasticsearch:2.4
- docker pull elasticsearch:5.2
- docker pull elasticsearch:5.3

script:
- make $TASKS

after_script:
- codecov

cache:
- apt
- pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

env:
  global:
  - TASKS="cov setup-check" TEST_ARGS="--no-pull -rsxX -v --es-tag=1.7 --es-tag=2.4 --es-tag=5.2 --es-tag=5.3"
  matrix:
  - PYTHONASYNCIODEBUG=1
  - PYTHONASYNCIODEBUG=
matrix:
  include:
  - python: "3.6"
    env: TASKS="cmp"

deploy:
  provider: pypi
  user: andrew.svetlov
  password:
    secure: DoeWNoPsOJzD9MheKAAnBiycRs6bnsro0PNmfe5Rj0N3tS0ocm6oyOOUtmLqGX41C97neremBUxTokp6lE9awmmJbTxUacOa6yleoPAr0VTphWx4vMuQSLNON8pUhjnHJbY3+1/34/BV3b4XL+jegiikh3tpeOvCVDfXh4JORRI=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    all_branches: true
    python: 3.5
